In [1]:
import numpy as np

In [7]:
a=np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [9]:
for i in a:
    print(i**(1/2))#sqrt of i

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
#iteration over the rows

In [11]:
students=np.array([['ravi','suresh','veena','Geetha'],#customers
                   [65,56,78,99],#electonics
                   [71,82,79,92]])#consumer products
for i in students:
    print('i=',i)

i= ['ravi' 'suresh' 'veena' 'Geetha']
i= ['65' '56' '78' '99']
i= ['71' '82' '79' '92']


In [19]:
AMZ_customers=np.array([['ravi','suresh','veena','Geetha'],#customers
                   [65,56,78,99],#electonics
                   [71,82,79,92]])#consumer products

for elements in AMZ_customers.flatten():
    
    print(elements)#it is consider as c order flatteing

ravi
suresh
veena
Geetha
65
56
78
99
71
82
79
92


In [20]:
for elements in AMZ_customers.flatten(order='F'):
    
    print(elements)#it is consider as row wise flatteing

ravi
65
71
suresh
56
82
veena
78
79
Geetha
99
92


In [ ]:
#introduction to nditer

In [21]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
for i in np.nditer(x):
    print(i)#c_order..>column wise

0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
for i in np.nditer(x,order='F'):
    print(i)#c_order..>column wise

0
4
8
1
5
9
2
6
10
3
7
11


In [32]:
for i in np.nditer(x,order='F',flags=['external_loop']):
    print(i)#columns have been converted into rows

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
